"""Add new fields based on CSV analysis

Revision ID: 03f4fbd77d75
Revises: 890ac604277a
Create Date: 2026-03-24 06:34:54.038466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f4fbd77d75'
down_revision: Union[str, None] = '890ac604277a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
