"""migrate_client_fields_to_implementation

Revision ID: 1715dc6dd265
Revises: a0a291f4256f
Create Date: 2026-04-02 04:46:28.321096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1715dc6dd265'
down_revision: Union[str, None] = 'a0a291f4256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementations', sa.Column('poc_1', sa.String(), nullable=True))
    op.add_column('implementations', sa.Column('poc_2', sa.String(), nullable=True))
    op.add_column('implementations', sa.Column('license_uat', sa.String(), nullable=True))
    op.add_column('implementations', sa.Column('license_prod', sa.String(), nullable=True))
    op.add_column('implementations', sa.Column('uat_version', sa.String(), nullable=True))
    op.add_column('implementations', sa.Column('prod_version', sa.String(), nullable=True))
    op.drop_column('implementations', 'version_details')
    op.drop_column('implementations', 'poc_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementations', sa.Column('poc_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('implementations', sa.Column('version_details', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('implementations', 'prod_version')
    op.drop_column('implementations', 'uat_version')
    op.drop_column('implementations', 'license_prod')
    op.drop_column('implementations', 'license_uat')
    op.drop_column('implementations', 'poc_2')
    op.drop_column('implementations', 'poc_1')
    # ### end Alembic commands ###
