"""add_milestone_stage_to_logs

Revision ID: 28e297a4ca48
Revises: ac4b92c20818
Create Date: 2026-03-31 16:01:03.776127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28e297a4ca48'
down_revision: Union[str, None] = 'ac4b92c20818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementation_logs', sa.Column('milestone_stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implementation_logs', 'milestone_stage')
    # ### end Alembic commands ###
