"""Add remarks to task

Revision ID: 3970b3afae61
Revises: 5b1176a53421
Create Date: 2026-03-24 07:19:42.485269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3970b3afae61'
down_revision: Union[str, None] = '5b1176a53421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'remarks')
    # ### end Alembic commands ###
