"""Add build_version and database_version

Revision ID: 5b1176a53421
Revises: 5b2a0228bfbc
Create Date: 2026-03-24 07:15:21.077877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b1176a53421'
down_revision: Union[str, None] = '5b2a0228bfbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('database_version', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('build_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'build_version')
    op.drop_column('clients', 'database_version')
    # ### end Alembic commands ###
