"""Add hashed_password and CSV fields

Revision ID: 5b2a0228bfbc
Revises: 0b6819b3031d
Create Date: 2026-03-24 06:36:09.440268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a0228bfbc'
down_revision: Union[str, None] = '0b6819b3031d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('database_type', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('remarks', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('hostname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'hashed_password')
    op.drop_column('locations', 'hostname')
    op.drop_column('clients', 'remarks')
    op.drop_column('clients', 'database_type')
    # ### end Alembic commands ###
