"""remove_timezone_from_users

Revision ID: 6512a85edc8e
Revises: b5e561f41daa
Create Date: 2026-05-10 09:05:38.395402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6512a85edc8e'
down_revision: Union[str, None] = 'b5e561f41daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(), server_default=sa.text("'UTC'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
