"""remove_unused_fields_from_client

Revision ID: 80471274c9db
Revises: 1715dc6dd265
Create Date: 2026-04-02 05:08:40.398624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80471274c9db'
down_revision: Union[str, None] = '1715dc6dd265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'poc_2')
    op.drop_column('clients', 'license_prod')
    op.drop_column('clients', 'uat_version')
    op.drop_column('clients', 'zone')
    op.drop_column('clients', 'prod_version')
    op.drop_column('clients', 'license_uat')
    op.drop_column('clients', 'client_location')
    op.drop_column('clients', 'poc_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('poc_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('client_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('license_uat', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('prod_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('uat_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('license_prod', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('poc_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
