"""add_is_active_to_tasks

Revision ID: a0a291f4256f
Revises: 28e297a4ca48
Create Date: 2026-03-31 16:39:37.865636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a291f4256f'
down_revision: Union[str, None] = '28e297a4ca48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('implementation_tasks', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implementation_tasks', 'is_active')
    # ### end Alembic commands ###
