"""add_status_remarks_to_implementation

Revision ID: ac4b92c20818
Revises: a1b2c3d4e5f6
Create Date: 2026-03-30 14:01:27.290305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4b92c20818'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('implementation_tasks', 'section')
    op.add_column('implementations', sa.Column('status_remarks', sa.String(), nullable=True))
    op.create_index(op.f('ix_milestone_sections_id'), 'milestone_sections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milestone_sections_id'), table_name='milestone_sections')
    op.drop_column('implementations', 'status_remarks')
    op.add_column('implementation_tasks', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
