"""Add tags to client

Revision ID: af44f19970f6
Revises: 3970b3afae61
Create Date: 2026-03-24 07:41:15.589880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af44f19970f6'
down_revision: Union[str, None] = '3970b3afae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'tags')
    # ### end Alembic commands ###
