"""Add extended metadata to client

Revision ID: d554e1582b40
Revises: bbcb93c6761c
Create Date: 2026-03-24 09:32:55.542605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd554e1582b40'
down_revision: Union[str, None] = 'bbcb93c6761c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('zone', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('client_location', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('poc_1', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('poc_2', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('license_uat', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('license_prod', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('uat_version', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('prod_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'prod_version')
    op.drop_column('clients', 'uat_version')
    op.drop_column('clients', 'license_prod')
    op.drop_column('clients', 'license_uat')
    op.drop_column('clients', 'poc_2')
    op.drop_column('clients', 'poc_1')
    op.drop_column('clients', 'client_location')
    op.drop_column('clients', 'zone')
    # ### end Alembic commands ###
